---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "app-config"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/component: "app"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
data:
  API_HTTP: "http://api-service:{{ .Values.parameters.api.port_http }}"
  services__api__http__0: "http://api-service:{{ .Values.parameters.api.port_http }}"
