apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.postgresql
  version: v1
  ignoreErrors: true
  metadata:
  - name: connectionString
    value: "Host=localhost;Port=5432;Database=weatherdb;Username=postgres;Password=postgres;SSL Mode=Disable;"
