apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.postgresql
  version: v1
  ignoreErrors: true
  metadata:
  - name: connectionString
    value: "host=localhost port=5432 dbname=weatherdb user=postgres password=postgres sslmode=disable"

