---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "telemetryprocessor-service"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/component: "telemetryprocessor"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
spec:
  type: "ClusterIP"
  selector:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/component: "telemetryprocessor"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
  ports:
    - name: "http"
      protocol: "TCP"
      port: {{ .Values.parameters.telemetryprocessor.port_http | int }}
      targetPort: {{ .Values.parameters.telemetryprocessor.port_http | int }}
