/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": process.env.region,
    "aws_appsync_graphqlEndpoint": process.env.endpoint,
    "aws_appsync_region": process.env.region,
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": process.env.apiKey
};


export default awsmobile;